class UserLocator:
    CUSTOMER = "//li[@data-modular-id='main_menu_team_clients']"
    CLIENT = "//a[@href='/users']"
    DASHBOARD = "//I[@class='ti-home']"
    CREATE_USER = "//button[@data-modal-title='Create A New User']"
    CLICK_COMPANY = "//span[@aria-labelledby='select2-clientid-container']"
    SEARCH_COMPANY = "//span[@class='select2-search select2-search--dropdown']//input"
    SELECT_COMPANY = "//li[contains(text(),'Dellon Inc')]"
    FIRST_NAME = "//div[@class='col-sm-12 col-lg-9']//input[@id='first_name']"
    LAST_NAME = "//div[@class='col-sm-12 col-lg-9']//input[@id='last_name']"
    EMAIL = "//div[@class='col-sm-12 col-lg-9']//input[@id='email']"
    PHONE = "//div[@class='col-sm-12 col-lg-9']//input[@id='phone']"
    POSITION = "//div[@class='col-sm-12 col-lg-9']//input[@id='position']"
    TIMEZONE = "//span[@aria-labelledby='select2-timezone-container']"
    VIETNAM = "//li[contains(text(),'Asia/Ho_Chi_Minh')]"
    SUBMIT_BTN = "#commonModalSubmitButton"
    SEARCH = "#search_query"
    EDIT_BUTTON = "//button[@data-modal-title='Edit User']"
    BERLIN = "//li[contains(text(),'Europe/Berlin')]"
    ENABLE_PROFILE = "//span[@class='lever switch-col-light-blue']"
    TWITTER = "#social_twitter"
    FACEBOOK = "#social_facebook"
    LINKEDIN = "#social_linkedin"
    GITHUB = "#social_github"
    DIRBBLE = "#social_dribble"
    CLICK_USER = "//tbody[@id='contacts-td-container']//tr[1]//td[2]"
    VIEW_AVATAR = "//img[@class='img-circle']"
    VIEW_USER_NAME = "//h4[contains(@class,'card-title')]"
    VIEW_EMAIL = "//h6[@class='card-subtitle']"
    VIEW_USER_TEXT = "//span[@class='label label-outline-success']"
    VIEW_PHONE = "//div[@class='card-body p-t-0']//h6[1]"
    VIEW_JOB_TITLE = "//div[@class='card-body p-t-0']//h6[2]"
    VIEW_DATE = "//div[@class='card-body p-t-0']//h6[3]"
    VIEW_LAST_SEEN = "//div[@class='card-body p-t-0']//h6[4]"
    CLOSE_BUTTON = "#commonModalExtraCloseIcon"
    DELETE_BUTTON = "//button[@data-confirm-title='Delete User']"
    CONFIRM_DELETE = "//button[@class='btn btn-sm btn-outline-danger']"
    REQUEST_SUCCESSFULL_MESSAGE = "//div[@class='noty_message']"