name: Deploy Allure Report ttt

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Build Allure report (ví dụ bạn generate sẵn ra thư mục ./allure-report)
      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          echo "<html><body><h1>Test Report</h1></body></html>" > allure-report/index.html

      # 3️⃣ Deploy lên gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
