name: Test GH Pages Push Permission

on:
  push:
    branches: [ main ]  # khi push lên main, workflow này sẽ chạy

jobs:
  test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # cấp quyền ghi cho GITHUB_TOKEN

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cấu hình git và test push
      - name: Test push permission
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          echo "test $(date)" > test.txt
          git add test.txt
          git commit -m "Test push permission" || echo "No changes to commit"
          git push origin HEAD:gh-pages --force
